MONGO_DB_HOST = u'127.0.0.1'
MONGO_DB_PORT = 27017
MONGO_DB_NAME = u'tesis2'
MONGO_DB_USER = u'root'
MONGO_DB_PASSWORD = u'password'
DB_COL_TWEETS = u'tweets'
DB_COL_USERS = u'users'
DB_COL_UNLABELED_TWEETS = u'unlabeled_tweets'
DB_COL_UNLABELED_USERS= u'unlabeled_users'
